version: '3.1'

services:
  mysqldb:
    image: mysql
    env_file: ./.env
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $PASSWORD
    ports:
      - 3306:3306
  nodeapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mysqldb
    image: projetocrudapi
    env_file: ./.env
    ports:
      - $PORT:$PORT
